name: Python application
on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
  schedule:
    - cron:  '0 */8 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout actions
      uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
        cache: 'pip'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip cache purge
        pip install requests
    - name: run py script
      run: |
        python cve_description.py
    - name: commit
      run: |
        git config --global user.email mrwq@qq.com
        git config --global user.name mrwq
        git add .
        git commit -m "update" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
